### ISSUE TITLE
This isn't C

### ISSUE THREAD

**Issue by 2mac** [davehtaylor/cpp_practice#1]
*slaps wrist*

**Comment by davehtaylor** [comment]
Lol Sorry about that. I'll be having an OOP class coming up in the summer. It wanted some experience with C++ before hand. So I'm trying to prepare myself.

**Comment by 2mac** [comment]
I recommend you watch [this series](https://www.youtube.com/watch?v=QM1iUe6IofM) when you get a chance. Even if you end up not agreeing with it (I largely do agree with it), it can still give you a better perspective and help you make programs that don't suck as much. :)

**Comment by davehtaylor** [comment]
Thanks! I'll definitely check it out
